# Generated by Django 5.1.5 on 2025-02-28 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_auto_20250224_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planchoice',
            old_name='plan',
            new_name='plan_code',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='payment_provider_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(default='', max_length=255, verbose_name='External subscription ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='client.planchoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planchoice',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Plan Cost'),
        ),
        migrations.AlterField(
            model_name='planchoice',
            name='description1',
            field=models.CharField(max_length=300, verbose_name='Plan description 1:'),
        ),
        migrations.AlterField(
            model_name='planchoice',
            name='description2',
            field=models.CharField(max_length=300, verbose_name='Plan description 2:'),
        ),
        migrations.AlterField(
            model_name='planchoice',
            name='external_api_url',
            field=models.CharField(max_length=2000, unique=True, verbose_name='External API URL'),
        ),
        migrations.AlterField(
            model_name='planchoice',
            name='external_style_json',
            field=models.CharField(max_length=2000, verbose_name='External Style (json)'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Subscription Cost'),
        ),
    ]
