# Generated by Django 5.1.5 on 2025-02-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=3000, verbose_name='Content'),
        ),
    ]
